### ISSUE TITLE
Problemas menores

### ISSUE THREAD

**Issue by amnet04** [drumsoverbogota/metadatos#1]
La conexión no funciona con la versión 3.0 de pymongo que fue la que pip instaló por defecto en el servidor, se debió hacer un downgrade a la versión 2.8. (Información optenida en: https://github.com/MongoEngine/mongoengine/issues/935)

**Comment by drumsoverbogota** [comment]
Listo Carlos, no había tenido en cuenta eso

**Comment by amnet04** [comment]
Ok, solo era para documentar la instalación :D
